### ISSUE TITLE
Installation issue with vs2017

### ISSUE THREAD

**Issue by darewreck54** [deadlydog/VS.DiffAllFiles#13]
I tried to install the extension for vs2017 but get the follow exception thrown:

7/20/2017 10:30:53 PM - 	Name               : Diff All Files for VS2017
7/20/2017 10:30:53 PM - 	Author             : deadlydog
7/20/2017 10:30:53 PM - 	Version            : 1.0.1
7/20/2017 10:30:53 PM - 	Description        : Quickly compare changes to all files in Git (staged/unstaged files or a commit) or TFS (shelveset, changeset, or with pending changes).
7/20/2017 10:30:53 PM - 	Locale             : en-US
7/20/2017 10:30:53 PM - 	MoreInfoURL        : https://github.com/deadlydog/VS.DiffAllFiles
7/20/2017 10:30:53 PM - 	InstalledByMSI     : False
7/20/2017 10:30:53 PM - 	SupportedFrameworkVersionRange : [4.5,)
7/20/2017 10:30:53 PM - 
7/20/2017 10:30:53 PM - 	SignatureState     : Unsigned
7/20/2017 10:30:53 PM - 	Supported Products : 
7/20/2017 10:30:53 PM - 		Microsoft.VisualStudio.Community
7/20/2017 10:30:53 PM - 			Version : [15.0]
7/20/2017 10:30:53 PM - 
7/20/2017 10:30:53 PM - 	References         : 
7/20/2017 10:30:53 PM - 		-------------------------------------------------------
7/20/2017 10:30:53 PM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
7/20/2017 10:30:53 PM - 		Name         : Visual Studio MPF 15.0
7/20/2017 10:30:53 PM - 		Version      : [15.0,16.0)
7/20/2017 10:30:53 PM - 		MoreInfoURL  : 
7/20/2017 10:30:53 PM - 		Nested       : No
7/20/2017 10:30:53 PM - 
7/20/2017 10:30:53 PM - 	Prerequisites      : 
7/20/2017 10:30:53 PM - 		-------------------------------------------------------
7/20/2017 10:30:53 PM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Core
7/20/2017 10:30:53 PM - 		Name         : Managed Desktop Workload Core
7/20/2017 10:30:53 PM - 		Version      : [15.0.26208.0,16.0)
7/20/2017 10:30:53 PM - 
7/20/2017 10:30:53 PM - 		-------------------------------------------------------
7/20/2017 10:30:53 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/20/2017 10:30:53 PM - 		Name         : Visual Studio core editor
7/20/2017 10:30:53 PM - 		Version      : [15.0.26208.0,16.0)
7/20/2017 10:30:53 PM - 
7/20/2017 10:30:53 PM - Signature Details...
7/20/2017 10:30:53 PM - 	Extension is not signed.
7/20/2017 10:30:53 PM - 
7/20/2017 10:30:53 PM - Searching for applicable products...
7/20/2017 10:30:53 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
7/20/2017 10:30:53 PM - Found installed product - Microsoft Visual Studio Premium 2013 
7/20/2017 10:30:53 PM - Found installed product - Microsoft Visual Studio Professional 2013
7/20/2017 10:30:53 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
7/20/2017 10:30:53 PM - Found installed product - Global Location
7/20/2017 10:30:53 PM - Found installed product - Visual Studio Community 2017
7/20/2017 10:30:53 PM - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Thanks,
Derek

**Comment by darewreck54** [comment]
installation issue .  Nevermind
