### ISSUE TITLE
Cannot convert TrueToVisibleConverter to type Metadata

### ISSUE THREAD

**Issue by deadlydog** [deadlydog/VS.DiffAllFiles#4]
Copied from a [VS marketplace review comment](https://marketplace.visualstudio.com/items?itemName=deadlydog.DiffAllFilesforVS2015#review-details).

---

The tool is good but it gives me an exception
```
System.ArgumentException: Object of type 'System.Collections.Generic.List`1[System.Lazy`2[Microsoft.TeamFoundation.Controls.ITeamExplorerNavigationLink,Microsoft.TeamFoundation.Controls.WPF.Converters.TrueToVisibleConverter]]' cannot be converted to type 'System.Collections.Generic.List`1[System.Lazy`2[Microsoft.TeamFoundation.Controls.ITeamExplorerNavigationItem,Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.ITeamExplorerNavigationItemMetadata]]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.SetImportingMember(Object part, MemberInfo member, Object value)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Sati
```

**Comment by gb2017** [comment]
I am using Visual Studio 2015 and TFS. Whenever I open any project, my team explorer home page window looks like the image included.

![capture](https://cloud.githubusercontent.com/assets/24918893/21648153/8e6ed22c-d262-11e6-921e-8411295ec8dc.PNG)

**Comment by deadlydog** [comment]
Hmmm, that is very strange, as the Diff All Files extension does not show up anywhere on that home page; it only shows up on the Pending Changes / Changeset Details windows. If you disable the Diff All Files extension does the problem go away?

**Comment by gb2017** [comment]
I don't know what or where the problem was but it got solved when I installed the latest update (update 3) for visual studio 2015. Thanks a lot!!
I had the toolbar before when I installed fresh VS2015 but somehow it disappeared. Do you know why this could be happening?

**Comment by deadlydog** [comment]
I'm glad to hear that the update fixed it.

> I had the toolbar before when I installed fresh VS2015 but somehow it disappeared. Do you know why this could be happening?

Which toolbar are you referring to? The Diff All Files section in the Pending Changes pane? If so, have you tried just uninstalling and reinstalling Diff All Files?

**Comment by gb2017** [comment]
There was a TFS Compare toolbar which was same as Diff All.

**Comment by deadlydog** [comment]
So it was another extension that you had installed? I would just try re-installing it.

Or if you are referring to the list of files that shows up in the Pending Changes / Changeset panes, I'm not sure how you would restore that.

If it's just a built-in VS toolbar (not a separate extension), then perhaps you can find it in the `View` -> `Toolbars` VS menu.

**Comment by gb2017** [comment]
It was a VS built-in toolbar which disappeared. The Toolbar name was 'Tfs Compare'.

**Comment by deadlydog** [comment]
Maybe [this video](https://www.youtube.com/watch?v=yhAvtkfxGWo ) will help you restore it.

Also, would you mind adjusting your review rating that you gave [on this page](https://marketplace.visualstudio.com/items?itemName=deadlydog.DiffAllFilesforVS2015#review-details) now that Diff All Files is working for you again.

**Comment by deadlydog** [comment]
Closing this issue as installing VS 2015 Update 3 fixed the issue for @gb2017
